spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fangyan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hidialect.hidialect_ws.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path:F:/____Files/learning/System/Hi-Dialect

server:
  port: 8080
  tomcat:
    max-http-post-size: 50000000